src/Presentation/Mlp.Blog.WebMvc/Areas/Admin/Models/PageSetting.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mlp.Blog.WebMvc.Areas.Admin.Models
{
    public class PageSettingViewModel
    {
        public PgMenuViewModel MenuInfo { get; set; }


    }

    public class PgMenuViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string Area { get; set; }

        public string Controller { get; set; }

        public string Action { get; set; }

        public string FaIcon { get; set; }
        
        public string Anchor { get; set; }

        public string Tooltip { get; set; }

        public bool IsActive { get; set; }

    }

    public class CreatePageViewModel
    {
        public int TypePageId { get; set; }

        public SelectList TypePageList { get; set; }
    }
}

src/Presentation/Mlp.Blog.WebMvc/Areas/Admin/Controllers/PageSettingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Mlp.Blog.Core.Data;
using Mlp.Blog.Core.Domain.Page;
using Mlp.Blog.WebMvc.Areas.Admin.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Mlp.Blog.WebMvc.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class PageSettingController : Controller
    {
        private readonly IRepository<PgMenu, int> _repPgMenus;
        private readonly IRepository<PgTypeMenu, int> _repPgTypesOfMenu;

        public PageSettingController(IRepository<PgMenu, int> repPgMenus, IRepository<PgTypeMenu, int> repPgTypesOfMenu)
        {
            _repPgMenus = repPgMenus;
            _repPgTypesOfMenu = repPgTypesOfMenu;
        }
        [HttpGet]
        
        public IActionResult Index(int id)
        {
            var pgMenu = _repPgMenus.GetById(id);

            var model = new PageSettingViewModel();
            model.MenuInfo = new PgMenuViewModel
            {
                Id = pgMenu.Id,
                Name = pgMenu.Name,
                Action = pgMenu.Name,
                Anchor = pgMenu.Anchor,
                Area = pgMenu.Area,
                Controller = pgMenu.Controller,
                IsActive = pgMenu.IsActive
            };

            return View(model);
        }

        /// <summary>
        /// Update info for menu
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult UpdateMenuInfo(PgMenuViewModel model)
        {
            if (model.Id < 1)
                return NotFound();
            var entity = _repPgMenus.GetById(model.Id);
            entity.Name = model.Name;
            entity.IsActive = model.IsActive;
            entity.Action = model.Action;
            entity.Anchor = model.Anchor;
            entity.Area = model.Area;
            entity.Controller = model.Controller;
            entity.FaIcon = model.FaIcon;
            entity.Tooltip = model.Tooltip;
            _repPgMenus.Update(entity);

            return RedirectToAction("Index", new { id = model.Id });
        }

        /// <summary>
        /// Create new page
        /// </summary>
        /// <returns></returns>
        public IActionResult CreatePage()
        {
            var types = _repPgTypesOfMenu.GetAll().Select(x => new { Id = x.Id, Value = x.Name });
            var model = new CreatePageViewModel();
            model.TypePageList = new SelectList(types, "Id", "Value");
            return View(model);
        }
    }
}

src/Presentation/Mlp.Blog.WebMvc/Areas/Admin/Views/PageSetting/CreatePage.cshtml
@model CreatePageViewModel
@Html.PageTitle("Create new page")

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Info</h2>
                <ul class="nav navbar-right panel_toolbox ">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div id="wizard" class="form_wizard wizard_horizontal">
                    <ul class="wizard_steps anchor">
                        <li>
                            <a href="#step-1" class="selected" isdone="1" rel="1">
                                <span class="step_no">1</span>
                                <span class="step_descr">
                                    Step 1<br>
                                    <small>Choose a type of page</small>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#step-2" class="done" isdone="1" rel="2">
                                <span class="step_no">2</span>
                                <span class="step_descr">
                                    Step 2<br>
                                    <small>Step 2 description</small>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#step-3" class="done" isdone="1" rel="3">
                                <span class="step_no">3</span>
                                <span class="step_descr">
                                    Step 3<br>
                                    <small>Step 3 description</small>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#step-4" class="done" isdone="1" rel="4">
                                <span class="step_no">4</span>
                                <span class="step_descr">
                                    Step 4<br>
                                    <small>Step 4 description</small>
                                </span>
                            </a>
                        </li>
                    </ul>

                    <div class="stepContainer">
                        <div id="step-1" class="content" style="display: block;">
                            <form class="form-horizontal form-label-left">
                                <div class="form-group">
                                    <label class="control-label col-md-2 col-sm-2 col-xs-12">
                                        Type of page <span class="required">*</span>
                                    </label>
                                    <div class="col-md-3 col-sm-3 col-xs-12">
                                        <select asp-for="TypePageId" asp-items="@Model.TypePageList" class="form-control col-md-7 col-xs-12"></select>                                       
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div id="step-2" class="content" style="display: none;">
                            <h2 class="StepTitle">Step 2 Content</h2>
                            <p>
                                do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                                fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                            </p>
                            <p>
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor
                                in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                            </p>
                        </div>
                        <div id="step-3" class="content" style="display: none;">
                            <h2 class="StepTitle">Step 3 Content</h2>
                            <p>
                                sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore
                                eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                            </p>
                            <p>
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor
                                in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                            </p>
                        </div>
                        <div id="step-4" class="content" style="display: none;">
                            <h2 class="StepTitle">Step 4 Content</h2>
                            <p>
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                                Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                            </p>
                            <p>
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor
                                in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                            </p>
                            <p>
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor
                                in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                            </p>
                        </div>
                    </div>
                    @*<div class="actionBar">
                        <div class="msgBox">
                            <div class="content"></div>
                            <a href="#" class="close">X</a>
                        </div>
                        <div class="loader">Loading</div>
                        <a href="#" class="buttonFinish btn btn-default">Finish</a>
                        <a href="#" class="buttonNext btn btn-success">Next</a>
                        <a href="#" class="buttonPrevious btn btn-primary buttonDisabled">Previous</a>
                    </div>*@
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script src="~/lib/smartWizard/jquery.smartWizard.js"></script>
    <!-- jQuery Smart Wizard -->
    <script>
        $(document).ready(function () {
            $('#wizard').smartWizard();

            //$('#wizard_verticle').smartWizard({
            //  transitionEffect: 'slide'
            //});

            $('.buttonNext').addClass('btn btn-success');
            $('.buttonPrevious').addClass('btn btn-primary');
            $('.buttonFinish').addClass('btn btn-default');
        });
    </script>
    <!-- /jQuery Smart Wizard -->

}

src/Presentation/Mlp.Blog.WebMvc/Areas/Admin/Views/PageSetting/Index.cshtml
@model PageSettingViewModel

<div class="">
    @Html.PageTitle($"Edit {Model.MenuInfo.Name}")
    @Html.Partial("_EditMenuInfo", Model.MenuInfo)
</div>
@section styles{
    <link rel="stylesheet" href="~/lib/switchery/dist/switchery.css"/>
}

@section scripts{ 
<script src="~/lib/switchery/dist/switchery.js"></script>
}

src/Presentation/Mlp.Blog.WebMvc/Areas/Admin/Views/PageSetting/_EditMenuInfo.cshtml
@model PgMenuViewModel
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Menu info</h2>
                <ul class="nav navbar-right panel_toolbox ">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <br>
                <form form asp-action="UpdateMenuInfo" asp-controller="PageSetting" asp-anti-forgery="true" class="form-horizontal form-label-left">
                    <input type="hidden" asp-for="Id" />
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" asp-for="Name"></label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="text" asp-for="Name" class="form-control col-md-7 col-xs-12">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" asp-for="Action"></label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="text" asp-for="Action" class="form-control col-md-7 col-xs-12">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" asp-for="Controller"></label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="text" asp-for="Controller" class="form-control col-md-7 col-xs-12">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" asp-for="Area"></label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="text" asp-for="Area" class="form-control col-md-7 col-xs-12">
                                </div>
                            </div>
                            
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" asp-for="Anchor"></label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="text" asp-for="Anchor" class="form-control has-feedback-left">
                                    <span class="fa fa-anchor form-control-feedback left" aria-hidden="true"></span>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" asp-for="Tooltip"></label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="text" asp-for="Tooltip" class="form-control has-feedback-left">
                                    <span class="fa fa-info form-control-feedback left" aria-hidden="true"></span>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" asp-for="FaIcon">Icon</label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="text" asp-for="FaIcon" class="form-control has-feedback-left">
                                    <span class="fa fa-file-image-o form-control-feedback left" aria-hidden="true"></span>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" asp-for="IsActive"></label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="checkbox" asp-for="IsActive" class="js-switch" checked>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-md-1 ">
                            <button type="submit" class="btn btn-success">Update</button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>